version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: cms_postgres
    restart: always
    environment:
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: cms_password
      POSTGRES_DB: cms_db
    ports:
      - "5433:5432" # Puerto de tu PC : Puerto del contenedor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
